---
- name: Enable coolbits (overclocking)
  command: nvidia-xconfig --allow-empty-initial-configuration --enable-all-gpus --cool-bits=28 --separate-x-screens

- name: Reboot after setting coolbits
  shell: reboot && sleep 1
  async: 0
  poll: 0

- name: Wait for host to come back up
  local_action: wait_for host={{ ansible_ssh_host }} state=started
