---
- name: Enable coolbits (overclocking)
  command: nvidia-xconfig --allow-empty-initial-configuration --enable-all-gpus --cool-bits=28 --separate-x-screens

- name: Reboot after setting coolbits
  command: sleep 2 and /sbin/shutdown -r now "Software upgrade requires reboot"
  async: 1
  poll: 0
  ignore_errors: True

- name: Wait for host to come back up
  wait_for:
    host: "{{ ansible_ssh_host }}"
    state: started
    delay: 30
    timeout: 300
    connection: local
