---
- name: Create user
  lineinfile:
    path: /etc/rc.local
    regexp: '.+{{ nvidia_overclock_script_name }}$'
    line: '{{ nvidia_overclock_script_path }}'

- name: Check if coolbits enabled already
  command: awk /Coolbits/ /etc/X11/xorg.conf
  register: coolbits
  changed_when: false

- name: Enable coolbits (overclocking)
  command: nvidia-xconfig --allow-empty-initial-configuration --enable-all-gpus --cool-bits=28 --separate-x-screens
  when: coolbits.rc == 0

- name: Reboot after setting coolbits
  shell: reboot
  async: 0
  poll: 0
  when: coolbits.rc == 0

- name: Wait for host to come back up
  local_action: wait_for host={{ ansible_ssh_host }} state=started
  when: coolbits.rc == 0

- name: Generate script file
  template: src=nvidia-overclock.sh.j2
            dest={{ nvidia_overclock_script_path }}
            owner=root
            group=root
            mode=640
  notify:
  - script changed
