---
- name: Verify overclock script executed on startup
  lineinfile:
    path: /etc/rc.local
    regexp: '.+{{ nvidia_overclock_script_name }}$'
    insertbefore: '^exit 0$'
    line: '{{ nvidia_overclock_script_path }}'

- name: Generate script file
  template: src=nvidia-overclock.sh.j2
            dest={{ nvidia_overclock_script_path }}
            owner=root
            group=root
            mode=640
  notify:
  - script changed

- name: Check if xorg file exists
  stat:
    path: /etc/X11/xorg.conf
  register: xorgfile

- name: Create blank xorg.conf if it doesnt exist already
  file:
    path: /etc/X11/xorg.conf
    state: touch
  when: xorgfile.stat.exists == False

- name: Check if coolbits enabled already
  command: awk /Coolbits/ /etc/X11/xorg.conf
  register: coolbits
  changed_when: false

- name: Enable coolbits (overclocking)
  include: coolbits.yml
  when: coolbits.rc == 0
  notify:
  - script changed
